table Team
	lineageTag: f930b3ed-be2e-473c-85dc-e7810f5f2b99

	measure 'Total Matches' = ```
			
			VAR FirstTotalMatches = CALCULATE(COUNTA(PL_2008_2025[HomeTeam]),USERELATIONSHIP(PL_2008_2025[HomeTeam],Team[Teams]))
			RETURN 
			IF(ISFILTERED(Team[Teams]),FirstTotalMatches +COUNTA(PL_2008_2025[AwayTeam]),FirstTotalMatches)
			```
		formatString: 0
		lineageTag: 2c670fe0-b73c-4078-83b6-dcd0e726aff6

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Team","TableItemName":"Teams (clusters) 2","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"Team","TableItemName":"Teams (clusters) 3","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"Team","TableItemName":"Cards","ObjectType":4},"LinkType":"UsedInGroup"}]

	measure 'Total Goals' = ```
			
			VAR TotalHomeGoal = CALCULATE(SUM(PL_2008_2025[Full Time Home Goal]),USERELATIONSHIP(PL_2008_2025[HomeTeam],Team[Teams]))
			RETURN 
			IF(ISFILTERED(Team[Teams]),TotalHomeGoal +SUM(PL_2008_2025[Full Time Away Goal]), TotalHomeGoal+SUM(PL_2008_2025[Full Time Away Goal]))
			```
		formatString: 0
		lineageTag: 2f1d93fa-926d-4c48-b3dc-db392f974259

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Team","TableItemName":"Shots Accuracy & Finishing Clusters","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"Team","TableItemName":"Teams (clusters) 5","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"Team","TableItemName":"Teams (clusters) 6","ObjectType":4},"LinkType":"UsedInGroup"}]

	measure 'Total Red Cards' =
			
			var TotalHomeRed = CALCULATE(sum(PL_2008_2025[Home Team Red Cards]),USERELATIONSHIP(PL_2008_2025[HomeTeam],Team[Teams]))
			RETURN
			IF(ISFILTERED(Team[Teams]),TotalHomeRed+sum(PL_2008_2025[Away Team Red Cards]),TotalHomeRed+sum(PL_2008_2025[Away Team Red Cards]))
		formatString: 0
		lineageTag: b6857fd3-bd8d-4081-add2-b8a30e1e57c4

	measure 'Total Yellow Cards' =
			
			var TotalHomeYellow = CALCULATE(sum(PL_2008_2025[Home Team Yellow Cards]),USERELATIONSHIP(PL_2008_2025[HomeTeam],Team[Teams]))
			RETURN
			IF(ISFILTERED(Team[Teams]),TotalHomeYellow+sum(PL_2008_2025[Away Team Yellow Cards]),TotalHomeYellow+sum(PL_2008_2025[Away Team Yellow Cards]))
		formatString: 0
		lineageTag: 63f12b07-f5dd-482d-ab25-06023c9b1742

	column Teams
		dataType: string
		lineageTag: ba2d61e9-3b0a-413c-8d87-2074551896d8
		summarizeBy: none
		sourceColumn: Teams

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Team","TableItemName":"Shots Accuracy & Finishing Clusters","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"Team","TableItemName":"Cards","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"Team","TableItemName":"Teams (clusters) 4","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"Team","TableItemName":"Teams (clusters) 5","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"Team","TableItemName":"Teams (clusters) 6","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"Team","TableItemName":"Teams (clusters) 7","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"Team","TableItemName":"Teams (clusters) 8","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"Team","TableItemName":"Teams (clusters) 9","ObjectType":4},"LinkType":"UsedInGroup"}]

	/// Clusters for Teams
	column 'Teams (clusters)' = ```
			VAR __ClusterValue = 
				LOOKUPVALUE('ClusterMappingTable'[ClusterId], 'ClusterMappingTable'[Teams], 'Team'[Teams])
			
			RETURN
				SWITCH(
					__ClusterValue,
					BLANK(),
					BLANK(),
					CONCATENATE("Cluster", __ClusterValue)
				)
			```
		lineageTag: 79dad460-60fd-4e1b-90d7-9b2a096c189b
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Team"
				          }
				        },
				        "Property": "Teams"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"t","Entity":"Team"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"}}],"PartitionTable":{"Definition":{"TableDefinition":{"Version":2,"From":[{"Name":"p","Entity":"PL_2009_2019"},{"Name":"t","Entity":"Team"}],"Where":[],"OrderBy":[],"Select":[{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"Team.Teams"},"Name":"Team.Teams"},{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"clusterId"},"Name":"clusterId"}],"GroupBy":[],"Transform":[{"Name":"KMeansClustering","Algorithm":"KMeansClustering","Input":{"Parameters":[{"Literal":{"Value":"-1L"},"Name":"NumberOfClusters"}],"Table":{"Name":"input0","Columns":[{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"M Shot Accuracy"},"Name":"PL_2009_2019.M Shot Accuracy"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"M Finishing"},"Name":"PL_2009_2019.M Finishing"}},{"Role":"Item","Expression":{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"},"Name":"Team.Teams"}}]}},"Output":{"Table":{"Name":"output0","Columns":[{"Expression":{"Column":{"Expression":{"TransformTableRef":{"Source":"input0"}},"Property":"Team.Teams"},"Name":"Team.Teams"}},{"Role":"Series","Expression":{"TransformOutputRoleRef":{"Role":"ClusterId"},"Name":"clusterId"}}]}}}]},"ItemIdColumns":["Team.Teams"],"PartitionIdColumn":"clusterId","Partitions":[{"PartitionIds":[{"Literal":{"Value":"null"}}]}],"DefaultPartitionPrefix":"Cluster"},"Result":{"TableName":"ClusterMappingTable","PartitionIdColumn":"ClusterId","ItemIdMappings":[[{"PartitionTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"ClusterMappingTable"}},"Property":"Teams"}},"SourceTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"Team"}},"Property":"Teams"}}}]]}}}

		annotation SummarizationSetBy = Automatic

	/// Clusters for Teams
	column 'Teams (clusters) 2' = ```
			VAR __ClusterValue = 
				LOOKUPVALUE('ClusterMappingTable 2'[ClusterId], 'ClusterMappingTable 2'[Teams], 'Team'[Teams])
			
			RETURN
				SWITCH(
					__ClusterValue,
					BLANK(),
					BLANK(),
					CONCATENATE("Cluster", __ClusterValue)
				)
			```
		lineageTag: 5453ce48-fbd9-4fb6-9c96-dbb640b04922
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Team"
				          }
				        },
				        "Property": "Teams"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"t","Entity":"Team"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"}}],"PartitionTable":{"Definition":{"TableDefinition":{"Version":2,"From":[{"Name":"p","Entity":"PL_2009_2019"},{"Name":"t","Entity":"Team"}],"Where":[],"OrderBy":[],"Select":[{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"Team.Teams"},"Name":"Team.Teams"},{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"clusterId"},"Name":"clusterId"}],"GroupBy":[],"Transform":[{"Name":"KMeansClustering","Algorithm":"KMeansClustering","Input":{"Parameters":[{"Literal":{"Value":"-1L"},"Name":"NumberOfClusters"}],"Table":{"Name":"input0","Columns":[{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"Yellow / Match"},"Name":"PL_2009_2019.Yellow / Match"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"Red / Match"},"Name":"PL_2009_2019.Red / Match"}},{"Role":"Item","Expression":{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"},"Name":"Team.Teams"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Total Matches"},"Name":"Team.Total Matches"}}]}},"Output":{"Table":{"Name":"output0","Columns":[{"Expression":{"Column":{"Expression":{"TransformTableRef":{"Source":"input0"}},"Property":"Team.Teams"},"Name":"Team.Teams"}},{"Role":"Series","Expression":{"TransformOutputRoleRef":{"Role":"ClusterId"},"Name":"clusterId"}}]}}}]},"ItemIdColumns":["Team.Teams"],"PartitionIdColumn":"clusterId","Partitions":[{"PartitionIds":[{"Literal":{"Value":"null"}}]}],"DefaultPartitionPrefix":"Cluster"},"Result":{"TableName":"ClusterMappingTable 2","PartitionIdColumn":"ClusterId","ItemIdMappings":[[{"PartitionTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"ClusterMappingTable 2"}},"Property":"Teams"}},"SourceTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"Team"}},"Property":"Teams"}}}]]}}}

		annotation SummarizationSetBy = Automatic

	/// Clusters for Teams
	column 'Teams (clusters) 3' = ```
			VAR __ClusterValue = 
				LOOKUPVALUE('ClusterMappingTable 3'[ClusterId], 'ClusterMappingTable 3'[Teams], 'Team'[Teams])
			
			RETURN
				SWITCH(
					__ClusterValue,
					BLANK(),
					BLANK(),
					CONCATENATE("Cluster", __ClusterValue)
				)
			```
		lineageTag: 47eb04a0-681b-4ce9-aa99-5b72421a115c
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Team"
				          }
				        },
				        "Property": "Teams"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"t","Entity":"Team"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"}}],"PartitionTable":{"Definition":{"TableDefinition":{"Version":2,"From":[{"Name":"p","Entity":"PL_2009_2019"},{"Name":"t","Entity":"Team"}],"Where":[{"Condition":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"Season"}}],"Values":[[{"Literal":{"Value":"'09/10'"}}]]}}}],"OrderBy":[],"Select":[{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"Team.Teams"},"Name":"Team.Teams"},{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"clusterId"},"Name":"clusterId"}],"GroupBy":[],"Transform":[{"Name":"KMeansClustering","Algorithm":"KMeansClustering","Input":{"Parameters":[{"Literal":{"Value":"-1L"},"Name":"NumberOfClusters"}],"Table":{"Name":"input0","Columns":[{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"SOT Conceded / Match"},"Name":"PL_2009_2019.SOT Conceded / Match"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"Goals Conceded / Match"},"Name":"PL_2009_2019.Goals Conceded / Match"}},{"Role":"Item","Expression":{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"},"Name":"Team.Teams"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Total Matches"},"Name":"Team.Total Matches"}}]}},"Output":{"Table":{"Name":"output0","Columns":[{"Expression":{"Column":{"Expression":{"TransformTableRef":{"Source":"input0"}},"Property":"Team.Teams"},"Name":"Team.Teams"}},{"Role":"Series","Expression":{"TransformOutputRoleRef":{"Role":"ClusterId"},"Name":"clusterId"}}]}}}]},"ItemIdColumns":["Team.Teams"],"PartitionIdColumn":"clusterId","Partitions":[{"PartitionIds":[{"Literal":{"Value":"null"}}]}],"DefaultPartitionPrefix":"Cluster"},"Result":{"TableName":"ClusterMappingTable 3","PartitionIdColumn":"ClusterId","ItemIdMappings":[[{"PartitionTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"ClusterMappingTable 3"}},"Property":"Teams"}},"SourceTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"Team"}},"Property":"Teams"}}}]]}}}

		annotation SummarizationSetBy = Automatic

	/// Clusters for Teams
	column 'Shots Accuracy & Finishing Clusters' = ```
			VAR __ClusterValue = 
				LOOKUPVALUE('ClusterMappingTable'[ClusterId], 'ClusterMappingTable'[Teams], 'Team'[Teams])
			
			RETURN
				SWITCH(
					__ClusterValue,
					BLANK(),
					BLANK(),
					CONCATENATE("Cluster", __ClusterValue)
				)
			```
		lineageTag: 64816abe-c4a7-49cc-85b9-06f5876b28d1
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Team"
				          }
				        },
				        "Property": "Teams"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"t","Entity":"Team"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"}}],"PartitionTable":{"Definition":{"TableDefinition":{"Version":2,"From":[{"Name":"p","Entity":"PL_2008_2025"},{"Name":"t","Entity":"Team"}],"Where":[],"OrderBy":[],"Select":[{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"Team.Teams"},"Name":"Team.Teams"},{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"clusterId"},"Name":"clusterId"}],"GroupBy":[],"Transform":[{"Name":"KMeansClustering","Algorithm":"KMeansClustering","Input":{"Parameters":[{"Literal":{"Value":"3L"},"Name":"NumberOfClusters"}],"Table":{"Name":"input0","Columns":[{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"M Shot Accuracy"},"Name":"PL_2009_2019.M Shot Accuracy"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"M Finishing"},"Name":"PL_2009_2019.M Finishing"}},{"Role":"Item","Expression":{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"},"Name":"Team.Teams"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Total Goals"},"Name":"Team.Total Goals"}}]}},"Output":{"Table":{"Name":"output0","Columns":[{"Expression":{"Column":{"Expression":{"TransformTableRef":{"Source":"input0"}},"Property":"Team.Teams"},"Name":"Team.Teams"}},{"Role":"Series","Expression":{"TransformOutputRoleRef":{"Role":"ClusterId"},"Name":"clusterId"}}]}}}]},"ItemIdColumns":["Team.Teams"],"PartitionIdColumn":"clusterId","Partitions":[{"PartitionIds":[{"Literal":{"Value":"null"}}]}],"DefaultPartitionPrefix":"Cluster"},"Result":{"TableName":"ClusterMappingTable","PartitionIdColumn":"ClusterId","ItemIdMappings":[[{"PartitionTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"ClusterMappingTable"}},"Property":"Teams"}},"SourceTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"Team"}},"Property":"Teams"}}}]]}}}

		annotation SummarizationSetBy = Automatic

	/// Clusters for Teams
	column Cards = ```
			VAR __ClusterValue = 
				LOOKUPVALUE('ClusterMappingTable 2'[ClusterId], 'ClusterMappingTable 2'[Teams], 'Team'[Teams])
			
			RETURN
				SWITCH(
					__ClusterValue,
					BLANK(),
					BLANK(),
					CONCATENATE("Cluster", __ClusterValue)
				)
			```
		lineageTag: b1b993f7-57c2-4cfe-9875-e1d043ca6978
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Team"
				          }
				        },
				        "Property": "Teams"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"t","Entity":"Team"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"}}],"PartitionTable":{"Definition":{"TableDefinition":{"Version":2,"From":[{"Name":"p","Entity":"PL_2008_2025"},{"Name":"t","Entity":"Team"}],"Where":[],"OrderBy":[],"Select":[{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"Team.Teams"},"Name":"Team.Teams"},{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"clusterId"},"Name":"clusterId"}],"GroupBy":[],"Transform":[{"Name":"KMeansClustering","Algorithm":"KMeansClustering","Input":{"Parameters":[{"Literal":{"Value":"3L"},"Name":"NumberOfClusters"}],"Table":{"Name":"input0","Columns":[{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"Yellow / Match"},"Name":"PL_2009_2019.Yellow / Match"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"Red / Match"},"Name":"PL_2009_2019.Red / Match"}},{"Role":"Item","Expression":{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"},"Name":"Team.Teams"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Total Matches"},"Name":"Team.Total Matches"}}]}},"Output":{"Table":{"Name":"output0","Columns":[{"Expression":{"Column":{"Expression":{"TransformTableRef":{"Source":"input0"}},"Property":"Team.Teams"},"Name":"Team.Teams"}},{"Role":"Series","Expression":{"TransformOutputRoleRef":{"Role":"ClusterId"},"Name":"clusterId"}}]}}}]},"ItemIdColumns":["Team.Teams"],"PartitionIdColumn":"clusterId","Partitions":[{"PartitionIds":[{"Literal":{"Value":"null"}}]}],"DefaultPartitionPrefix":"Cluster"},"Result":{"TableName":"ClusterMappingTable 2","PartitionIdColumn":"ClusterId","ItemIdMappings":[[{"PartitionTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"ClusterMappingTable 2"}},"Property":"Teams"}},"SourceTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"Team"}},"Property":"Teams"}}}]]}}}

		annotation SummarizationSetBy = Automatic

	/// Clusters for Teams
	column 'Teams (clusters) 4' = ```
			VAR __ClusterValue = 
				LOOKUPVALUE('ClusterMappingTable 3'[ClusterId], 'ClusterMappingTable 3'[Teams], 'Team'[Teams])
			
			RETURN
				SWITCH(
					__ClusterValue,
					BLANK(),
					BLANK(),
					CONCATENATE("Cluster", __ClusterValue)
				)
			```
		lineageTag: 25b820a3-c310-44a0-9347-7a19b0a6c1ff
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Team"
				          }
				        },
				        "Property": "Teams"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"t","Entity":"Team"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"}}],"PartitionTable":{"Definition":{"TableDefinition":{"Version":2,"From":[{"Name":"p","Entity":"PL_2008_2025"},{"Name":"t","Entity":"Team"}],"Where":[],"OrderBy":[],"Select":[{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"Team.Teams"},"Name":"Team.Teams"},{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"clusterId"},"Name":"clusterId"}],"GroupBy":[],"Transform":[{"Name":"KMeansClustering","Algorithm":"KMeansClustering","Input":{"Parameters":[{"Literal":{"Value":"3L"},"Name":"NumberOfClusters"}],"Table":{"Name":"input0","Columns":[{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"SOT Conceded / Match"},"Name":"PL_2009_2019.SOT Conceded / Match"}},{"Role":"Item","Expression":{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"},"Name":"Team.Teams"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"Goals Conceded / Match"},"Name":"PL_2009_2019.Goals Conceded / Match"}}]}},"Output":{"Table":{"Name":"output0","Columns":[{"Expression":{"Column":{"Expression":{"TransformTableRef":{"Source":"input0"}},"Property":"Team.Teams"},"Name":"Team.Teams"}},{"Role":"Series","Expression":{"TransformOutputRoleRef":{"Role":"ClusterId"},"Name":"clusterId"}}]}}}]},"ItemIdColumns":["Team.Teams"],"PartitionIdColumn":"clusterId","Partitions":[{"PartitionIds":[{"Literal":{"Value":"null"}}]}],"DefaultPartitionPrefix":"Cluster"},"Result":{"TableName":"ClusterMappingTable 3","PartitionIdColumn":"ClusterId","ItemIdMappings":[[{"PartitionTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"ClusterMappingTable 3"}},"Property":"Teams"}},"SourceTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"Team"}},"Property":"Teams"}}}]]}}}

		annotation SummarizationSetBy = Automatic

	/// Clusters for Teams
	column 'Teams (clusters) 5' = ```
			VAR __ClusterValue = 
				LOOKUPVALUE('ClusterMappingTable 4'[ClusterId], 'ClusterMappingTable 4'[Teams], 'Team'[Teams])
			
			RETURN
				SWITCH(
					__ClusterValue,
					BLANK(),
					BLANK(),
					CONCATENATE("Cluster", __ClusterValue)
				)
			```
		lineageTag: 43cb8f5c-32dd-40f7-bde5-42dcf0470f7c
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Team"
				          }
				        },
				        "Property": "Teams"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"t","Entity":"Team"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"}}],"PartitionTable":{"Definition":{"TableDefinition":{"Version":2,"From":[{"Name":"t","Entity":"Team"},{"Name":"p","Entity":"PL_2008_2025"}],"Where":[{"Condition":{"Not":{"Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"}}],"Values":[[{"Literal":{"Value":"null"}}]]}}}}}],"OrderBy":[],"Select":[{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"Team.Teams"},"Name":"Team.Teams"},{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"clusterId"},"Name":"clusterId"}],"GroupBy":[],"Transform":[{"Name":"KMeansClustering","Algorithm":"KMeansClustering","Input":{"Parameters":[{"Literal":{"Value":"-1L"},"Name":"NumberOfClusters"}],"Table":{"Name":"input0","Columns":[{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"M TotalShotsOnTarget"},"Name":"PL_2008_2025.M TotalShotsOnTarget"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Total Goals"},"Name":"Team.Total Goals"}},{"Role":"Item","Expression":{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"},"Name":"Team.Teams"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"M TotalShots"},"Name":"PL_2008_2025.M TotalShots"}}]}},"Output":{"Table":{"Name":"output0","Columns":[{"Expression":{"Column":{"Expression":{"TransformTableRef":{"Source":"input0"}},"Property":"Team.Teams"},"Name":"Team.Teams"}},{"Role":"Series","Expression":{"TransformOutputRoleRef":{"Role":"ClusterId"},"Name":"clusterId"}}]}}}]},"ItemIdColumns":["Team.Teams"],"PartitionIdColumn":"clusterId","Partitions":[{"PartitionIds":[{"Literal":{"Value":"null"}}]}],"DefaultPartitionPrefix":"Cluster"},"Result":{"TableName":"ClusterMappingTable 4","PartitionIdColumn":"ClusterId","ItemIdMappings":[[{"PartitionTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"ClusterMappingTable 4"}},"Property":"Teams"}},"SourceTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"Team"}},"Property":"Teams"}}}]]}}}

		annotation SummarizationSetBy = Automatic

	/// Clusters for Teams
	column 'Teams (clusters) 6' = ```
			VAR __ClusterValue = 
				LOOKUPVALUE('ClusterMappingTable 5'[ClusterId], 'ClusterMappingTable 5'[Teams], 'Team'[Teams])
			
			RETURN
				SWITCH(
					__ClusterValue,
					BLANK(),
					BLANK(),
					CONCATENATE("Cluster", __ClusterValue)
				)
			```
		lineageTag: 63f9d82b-b80c-47e1-87bb-15ec54cc2471
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Team"
				          }
				        },
				        "Property": "Teams"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"t","Entity":"Team"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"}}],"PartitionTable":{"Definition":{"TableDefinition":{"Version":2,"From":[{"Name":"t","Entity":"Team"},{"Name":"p","Entity":"PL_2008_2025"}],"Where":[{"Condition":{"Not":{"Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"}}],"Values":[[{"Literal":{"Value":"null"}}]]}}}}}],"OrderBy":[],"Select":[{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"Team.Teams"},"Name":"Team.Teams"},{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"clusterId"},"Name":"clusterId"}],"GroupBy":[],"Transform":[{"Name":"KMeansClustering","Algorithm":"KMeansClustering","Input":{"Parameters":[{"Literal":{"Value":"4L"},"Name":"NumberOfClusters"}],"Table":{"Name":"input0","Columns":[{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"M TotalShotsOnTarget"},"Name":"PL_2008_2025.M TotalShotsOnTarget"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Total Goals"},"Name":"Team.Total Goals"}},{"Role":"Item","Expression":{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"},"Name":"Team.Teams"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"M TotalShots"},"Name":"PL_2008_2025.M TotalShots"}}]}},"Output":{"Table":{"Name":"output0","Columns":[{"Expression":{"Column":{"Expression":{"TransformTableRef":{"Source":"input0"}},"Property":"Team.Teams"},"Name":"Team.Teams"}},{"Role":"Series","Expression":{"TransformOutputRoleRef":{"Role":"ClusterId"},"Name":"clusterId"}}]}}}]},"ItemIdColumns":["Team.Teams"],"PartitionIdColumn":"clusterId","Partitions":[{"PartitionIds":[{"Literal":{"Value":"null"}}]}],"DefaultPartitionPrefix":"Cluster"},"Result":{"TableName":"ClusterMappingTable 5","PartitionIdColumn":"ClusterId","ItemIdMappings":[[{"PartitionTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"ClusterMappingTable 5"}},"Property":"Teams"}},"SourceTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"Team"}},"Property":"Teams"}}}]]}}}

		annotation SummarizationSetBy = Automatic

	/// Clusters for Teams
	column 'Teams (clusters) 7' = ```
			VAR __ClusterValue = 
				LOOKUPVALUE('ClusterMappingTable 6'[ClusterId], 'ClusterMappingTable 6'[Teams], 'Team'[Teams])
			
			RETURN
				SWITCH(
					__ClusterValue,
					BLANK(),
					BLANK(),
					CONCATENATE("Cluster", __ClusterValue)
				)
			```
		lineageTag: 6aed2c3f-24f7-40ef-ab24-77f3a74f1de1
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Team"
				          }
				        },
				        "Property": "Teams"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"t","Entity":"Team"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"}}],"PartitionTable":{"Definition":{"TableDefinition":{"Version":2,"From":[{"Name":"t","Entity":"Team"},{"Name":"p","Entity":"PL_2008_2025"}],"Where":[{"Condition":{"Not":{"Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"}}],"Values":[[{"Literal":{"Value":"null"}}]]}}}}}],"OrderBy":[],"Select":[{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"Team.Teams"},"Name":"Team.Teams"},{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"clusterId"},"Name":"clusterId"}],"GroupBy":[],"Transform":[{"Name":"KMeansClustering","Algorithm":"KMeansClustering","Input":{"Parameters":[{"Literal":{"Value":"3L"},"Name":"NumberOfClusters"}],"Table":{"Name":"input0","Columns":[{"Role":"Item","Expression":{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"},"Name":"Team.Teams"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"Shots Per Match"},"Name":"PL_2008_2025.Shots Per Match"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"M Shot Accuracy"},"Name":"PL_2008_2025.M Shot Accuracy"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"Goals Per Match"},"Name":"PL_2008_2025.Goals Per Match"}}]}},"Output":{"Table":{"Name":"output0","Columns":[{"Expression":{"Column":{"Expression":{"TransformTableRef":{"Source":"input0"}},"Property":"Team.Teams"},"Name":"Team.Teams"}},{"Role":"Series","Expression":{"TransformOutputRoleRef":{"Role":"ClusterId"},"Name":"clusterId"}}]}}}]},"ItemIdColumns":["Team.Teams"],"PartitionIdColumn":"clusterId","Partitions":[{"PartitionIds":[{"Literal":{"Value":"null"}}]}],"DefaultPartitionPrefix":"Cluster"},"Result":{"TableName":"ClusterMappingTable 6","PartitionIdColumn":"ClusterId","ItemIdMappings":[[{"PartitionTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"ClusterMappingTable 6"}},"Property":"Teams"}},"SourceTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"Team"}},"Property":"Teams"}}}]]}}}

		annotation SummarizationSetBy = Automatic

	/// Clusters for Teams
	column 'Teams (clusters) 8' = ```
			VAR __ClusterValue = 
				LOOKUPVALUE('ClusterMappingTable 7'[ClusterId], 'ClusterMappingTable 7'[Teams], 'Team'[Teams])
			
			RETURN
				SWITCH(
					__ClusterValue,
					BLANK(),
					BLANK(),
					CONCATENATE("Cluster", __ClusterValue)
				)
			```
		lineageTag: 6c8c0e68-35fa-4bc9-8f8a-140d047c8eac
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Team"
				          }
				        },
				        "Property": "Teams"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"t","Entity":"Team"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"}}],"PartitionTable":{"Definition":{"TableDefinition":{"Version":2,"From":[{"Name":"t","Entity":"Team"},{"Name":"p","Entity":"PL_2008_2025"}],"Where":[{"Condition":{"Not":{"Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"}}],"Values":[[{"Literal":{"Value":"null"}}]]}}}}}],"OrderBy":[],"Select":[{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"Team.Teams"},"Name":"Team.Teams"},{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"clusterId"},"Name":"clusterId"}],"GroupBy":[],"Transform":[{"Name":"KMeansClustering","Algorithm":"KMeansClustering","Input":{"Parameters":[{"Literal":{"Value":"2L"},"Name":"NumberOfClusters"}],"Table":{"Name":"input0","Columns":[{"Role":"Item","Expression":{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"},"Name":"Team.Teams"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"Shots Per Match"},"Name":"PL_2008_2025.Shots Per Match"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"M Shot Accuracy"},"Name":"PL_2008_2025.M Shot Accuracy"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"Goals Per Match"},"Name":"PL_2008_2025.Goals Per Match"}}]}},"Output":{"Table":{"Name":"output0","Columns":[{"Expression":{"Column":{"Expression":{"TransformTableRef":{"Source":"input0"}},"Property":"Team.Teams"},"Name":"Team.Teams"}},{"Role":"Series","Expression":{"TransformOutputRoleRef":{"Role":"ClusterId"},"Name":"clusterId"}}]}}}]},"ItemIdColumns":["Team.Teams"],"PartitionIdColumn":"clusterId","Partitions":[{"PartitionIds":[{"Literal":{"Value":"null"}}]}],"DefaultPartitionPrefix":"Cluster"},"Result":{"TableName":"ClusterMappingTable 7","PartitionIdColumn":"ClusterId","ItemIdMappings":[[{"PartitionTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"ClusterMappingTable 7"}},"Property":"Teams"}},"SourceTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"Team"}},"Property":"Teams"}}}]]}}}

		annotation SummarizationSetBy = Automatic

	/// Clusters for Teams
	column 'Teams (clusters) 9' = ```
			VAR __ClusterValue = 
				LOOKUPVALUE('ClusterMappingTable 8'[ClusterId], 'ClusterMappingTable 8'[Teams], 'Team'[Teams])
			
			RETURN
				SWITCH(
					__ClusterValue,
					BLANK(),
					BLANK(),
					CONCATENATE("Cluster", __ClusterValue)
				)
			```
		lineageTag: 5bfe9f2e-a990-4c50-8c0a-a8cbdae557db
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Team"
				          }
				        },
				        "Property": "Teams"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"t","Entity":"Team"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"}}],"PartitionTable":{"Definition":{"TableDefinition":{"Version":2,"From":[{"Name":"t","Entity":"Team"},{"Name":"p","Entity":"PL_2008_2025"}],"Where":[{"Condition":{"Not":{"Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"}}],"Values":[[{"Literal":{"Value":"null"}}]]}}}}}],"OrderBy":[],"Select":[{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"Team.Teams"},"Name":"Team.Teams"},{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"clusterId"},"Name":"clusterId"}],"GroupBy":[],"Transform":[{"Name":"KMeansClustering","Algorithm":"KMeansClustering","Input":{"Parameters":[{"Literal":{"Value":"-1L"},"Name":"NumberOfClusters"}],"Table":{"Name":"input0","Columns":[{"Role":"Item","Expression":{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"Teams"},"Name":"Team.Teams"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"Shots Per Match"},"Name":"PL_2008_2025.Shots Per Match"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"M Shot Accuracy"},"Name":"PL_2008_2025.M Shot Accuracy"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"Goals Per Match"},"Name":"PL_2008_2025.Goals Per Match"}}]}},"Output":{"Table":{"Name":"output0","Columns":[{"Expression":{"Column":{"Expression":{"TransformTableRef":{"Source":"input0"}},"Property":"Team.Teams"},"Name":"Team.Teams"}},{"Role":"Series","Expression":{"TransformOutputRoleRef":{"Role":"ClusterId"},"Name":"clusterId"}}]}}}]},"ItemIdColumns":["Team.Teams"],"PartitionIdColumn":"clusterId","Partitions":[{"PartitionIds":[{"Literal":{"Value":"null"}}]}],"DefaultPartitionPrefix":"Cluster"},"Result":{"TableName":"ClusterMappingTable 8","PartitionIdColumn":"ClusterId","ItemIdMappings":[[{"PartitionTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"ClusterMappingTable 8"}},"Property":"Teams"}},"SourceTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"Team"}},"Property":"Teams"}}}]]}}}

		annotation SummarizationSetBy = Automatic

	partition Team = m
		mode: import
		source =
				let
				    Source = PL_2008_2025,
				    Keep = Table.SelectColumns(Source, {"HomeTeam","AwayTeam"}),
				    Unpivot = Table.UnpivotOtherColumns(Keep, {}, "TeamType", "Teams"),
				    Clean = Table.TransformColumns(Unpivot, {{"Teams", Text.Trim, type text}}),
				    NonBlank = Table.SelectRows(Clean, each [Teams] <> null and [Teams] <> ""),
				    DistinctTeams = Table.Distinct(Table.SelectColumns(NonBlank, {"Teams"})),
				    Sorted = Table.Sort(DistinctTeams, {{"Teams", Order.Ascending}})
				in
				    Sorted

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

